# Generated by Django 5.2.2 on 2026-08-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('exchange', models.CharField(default='NSE', max_length=20)),
            ],
        ),
    ]
